"""Add user_courses enrollment table

Revision ID: 7e57668c3af0
Revises: a7d7aac890a3
Create Date: 2026-08-09 15:39:27.954738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e57668c3af0'
down_revision: Union[str, None] = 'a7d7aac890a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
